# Generated by Django 4.0.6 on 2022-07-18 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LanguageWordList',
            new_name='Language',
        ),
    ]
