# Generated by Django 4.0.6 on 2022-07-18 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_languagewordlist_language'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Language',
            new_name='LanguageWords',
        ),
    ]
