# Generated by Django 4.0.6 on 2022-07-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_language_languagewords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlanguages',
            name='id',
        ),
        migrations.AlterField(
            model_name='userlanguages',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
