# Generated by Django 4.0.6 on 2022-07-18 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_userlanguages_id_alter_userlanguages_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlanguages',
            old_name='name',
            new_name='language_name',
        ),
        migrations.AddField(
            model_name='languagewords',
            name='language_name',
            field=models.ForeignKey(default='spanish', on_delete=django.db.models.deletion.CASCADE, to='user.userlanguages'),
            preserve_default=False,
        ),
    ]
