# Generated by Django 4.0.6 on 2022-07-18 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_name_userlanguages_language_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlanguages',
            name='n_words_learned',
        ),
    ]
